[build]
command = "npm run build"
publish = "dist"

[dev]
command = "npm run dev"

[images]
remote_images = ["https://a-us.storyblok.com/*"]

[context.previews]
    [[headers]]
        for = "/*"
        [headers.values]
            X-Robots-Tag = "noindex"