# merge main branch into previews branch

name: Auto merge
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge main into previews
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git fetch --unshallow
          git checkout previews
          git pull
          git merge --no-ff main -m "Auto merge from main into previews"
          git push
